# Generated by Django 2.0.3 on 2018-08-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cookies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleme_key', models.CharField(max_length=255)),
                ('url_appand', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('used_times', models.IntegerField(default=0)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_created=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=11)),
                ('points', models.IntegerField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_created=True)),
            ],
        ),
    ]
