# Generated by Django 2.0.3 on 2018-09-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='cookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleme_key', models.CharField(max_length=255)),
                ('url_appand', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('cookie', models.CharField(max_length=2000)),
                ('phone', models.CharField(max_length=11)),
                ('qq', models.CharField(max_length=20)),
                ('used_times', models.IntegerField(default=0)),
            ],
        ),
    ]
